---
# Queue configuration with weights (higher number = higher priority)
# Sidekiq will process 10 collection_sync jobs for every 1 default job
:queues:
  - [collection_sync, 10]  # High priority queue for collection syncing
  - [default, 1]           # Default queue with lower priority